#!/bin/bash

set -euo pipefail

cd /app/game/game/RuntimeData

rm -rf ArcenDebugLog.txt

ln -s /var/data/Save .
ln -s /var/data/ArcenDebugLog.txt .
ln -s /var/config/settings.bak .
ln -s /var/config/settings.dat .
