#!/bin/bash

set -euo pipefail

cd game-extract/data/noarch/game/RuntimeData

rm -r Save
rm ArcenDebugLog.txt

ln -s /var/data/Save .
ln -s /var/data/ArcenDebugLog.txt
ln -s /var/config/settings.bak .
ln -s /var/config/settings.dat .
