#!/bin/bash

if [ ! -e ${XDG_DATA_HOME}/.macromedia ]
then
    mkdir ${XDG_DATA_HOME}/.macromedia
fi

if [ ! -e ~/.macromedia ]
then
    ln -s ${XDG_DATA_HOME}/.macromedia ~/.macromedia
fi

cd /app/game/
./start.sh
